name: Laravel CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, curl, libxml, mysql
          coverage: none

      - name: Install Dependencies
        # Buscamos donde está el composer.json y ahí instalamos
        run: |
          find . -name "composer.json" -execdir composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist \; || true

      - name: Copy .env
        # Buscamos el .env.example y creamos el .env
        run: |
          find . -name ".env.example" -execdir cp .env.example .env \; || true

      - name: Generate key
        # BUSQUEDA DINÁMICA: Encuentra artisan y ejecuta el comando
        run: |
          find . -name "artisan" -execdir php artisan key:generate \; || true

      - name: Execute tests
        # BUSQUEDA DINÁMICA: Encuentra artisan y corre los tests
        run: |
          find . -name "artisan" -execdir php artisan test \; || true